// CARD(S)
export const FETCH_CARDS_DATA_SUCCESSFUL = 'FETCH_CARDS_DATA_SUCCESSFUL';
export const FETCH_CARDS_DATA_FAILED = 'FETCH_CARDS_DATA_FAILED';

// CARD
export const FETCH_CARD_DATA_SUCCESSFUL = 'FETCH_CARD_DATA_SUCCESSFUL';
export const FETCH_CARD_DATA_FAILED = 'FETCH_CARD_DATA_FAILED';
export const SET_CARD_DATA_SUCCESSFUL = 'SET_CARD_DATA_SUCCESSFUL';
export const SET_CARD_DATA_FAILED = 'SET_CARD_DATA_FAILED';

// FILTER
export const SET_FILTER_OPTIONS = 'SET_FILTER_OPTIONS';
export const CLEAR_FILTER_OPTIONS = 'CLEAR_FILTER_OPTIONS';

// STATE MANAGEMENT
export const IS_LOADING_CARDS_TRUE = 'IS_LOADING_CARDS_TRUE';
export const IS_LOADING_CARDS_FALSE = 'IS_LOADING_CARDS_FALSE';
export const IS_LOADING_CARD_TRUE = 'IS_LOADING_CARD_TRUE';
export const IS_LOADING_CARD_FALSE = 'IS_LOADING_CARD_FALSE';

// SPEC PRICES
export const SET_SPEC_PRICES_SUCCESSFUL = 'SET_SPEC_PRICES_SUCCESSFUL';
export const SET_SPEC_PRICES_FAILED = 'SET_SPEC_PRICES_FAILED';

// TCG PRICES
export const SET_TCG_PRICES_SUCCESSFUL = 'SET_TCG_PRICES_SUCCESSFUL';
export const SET_TCG_PRICES_FAILED = 'SET_TCG_PRICES_FAILED';

// TCG CATEGORIES
export const SET_PRICE_CATEGORY_LOW = 'SET_PRICE_CATEGORY_LOW';
export const SET_PRICE_CATEGORY_MID = 'SET_PRICE_CATEGORY_MID';
export const SET_PRICE_CATEGORY_HIGH = 'SET_PRICE_CATEGORY_HIGH';
export const SET_PRICE_CATEGORY_MARKET = 'SET_PRICE_CATEGORY_MARKET';
