// CARD(S)
export const FETCH_CARDS_DATA_SUCCESSFUL = 'FETCH_CARDS_DATA_SUCCESSFUL';
export const FETCH_CARDS_DATA_FAILED = 'FETCH_CARDS_DATA_FAILED';

// CARD
export const FETCH_CARD_DATA_SUCCESSFUL = 'FETCH_CARD_DATA_SUCCESSFUL';
export const FETCH_CARD_DATA_FAILED = 'FETCH_CARD_DATA_FAILED';
export const SET_CARD_DATA_SUCCESSFUL = 'SET_CARD_DATA_SUCCESSFUL';
export const SET_CARD_DATA_FAILED = 'SET_CARD_DATA_FAILED';

// STATE MANAGEMENT
export const IS_LOADING = 'IS_LOADING';

// SPEC PRICES
export const SET_SPEC_PRICES_SUCCESSFUL = 'SET_SPEC_PRICES_SUCCESSFUL';
export const SET_SPEC_PRICES_FAILED = 'SET_SPEC_PRICES_FAILED';

// TCG PRICES
export const SET_TCG_PRICES_SUCCESSFUL = 'SET_TCG_PRICES_SUCCESSFUL';
export const SET_TCG_PRICES_FAILED = 'SET_TCG_PRICES_FAILED';
