export const initState = {
  cardsReducer: {
    entities: {},
    result: [],
  },
  cardReducer: {},
  isLoadingReducer: {
    cards: false,
    card: false,
  },
  specPricesReducer: {},
  tcgPricesReducer: {},
};

export const fullState = {
  cardsReducer: {
    entities: {
      cards: {
        '1679': {
          id: 1679,
          card_name: 'Linden, the Steadfast Queen',
          set_name: 'Throne of Eldraine',
          language: '',
          foil: 0,
          tcg_productId: 199209,
          tcg_imageUrl:
            'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/199209_200w.jpg',
          tcg_groupId: 2494,
          tcg_url:
            'https://store.tcgplayer.com/magic/throne-of-eldraine/linden-the-steadfast-queen',
          tcg_price: {
            id: 5406,
            date: '2020-08-04',
            product_id: 199209,
            low_price: '0.14',
            mid_price: '0.50',
            high_price: '3.73',
            market_price: '0.40',
            direct_low_price: '0.37',
            sub_type_name: 'Normal',
            card: 1679,
          },
          spec_prices: [
            {
              id: 4231,
              price_percentages: {
                foil_low: -3.33,
                foil_mid: 233.33,
                foil_high: 1563.33,
                foil_market: 96.67,
                normal_low: -53.33,
                normal_mid: 66.67,
                normal_high: 1143.33,
                normal_market: 33.33,
              },
              date_purchased: '2019-12-31',
              quantity: 7,
              single_cost: '0.30',
              price: '0.19',
              total_cash: '2.11',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: "Dolly's Toys & Games",
              card: 1679,
            },
            {
              id: 4229,
              price_percentages: {
                foil_low: -12.12,
                foil_mid: 203.03,
                foil_high: 1412.12,
                foil_market: 78.79,
                normal_low: -57.58,
                normal_mid: 51.52,
                normal_high: 1030.3,
                normal_market: 21.21,
              },
              date_purchased: '2019-12-31',
              quantity: 6,
              single_cost: '0.33',
              price: '0.20',
              total_cash: '1.98',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'gacollectables',
              card: 1679,
            },
            {
              id: 4230,
              price_percentages: {
                foil_low: -12.12,
                foil_mid: 203.03,
                foil_high: 1412.12,
                foil_market: 78.79,
                normal_low: -57.58,
                normal_mid: 51.52,
                normal_high: 1030.3,
                normal_market: 21.21,
              },
              date_purchased: '2019-12-31',
              quantity: 6,
              single_cost: '0.33',
              price: '0.20',
              total_cash: '1.98',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'jtsquared',
              card: 1679,
            },
            {
              id: 4228,
              price_percentages: {
                foil_low: -23.68,
                foil_mid: 163.16,
                foil_high: 1213.16,
                foil_market: 55.26,
                normal_low: -63.16,
                normal_mid: 31.58,
                normal_high: 881.58,
                normal_market: 5.26,
              },
              date_purchased: '2019-12-31',
              quantity: 6,
              single_cost: '0.38',
              price: '0.25',
              total_cash: '2.28',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Slick Deals',
              card: 1679,
            },
            {
              id: 4227,
              price_percentages: {
                foil_low: -29.27,
                foil_mid: 143.9,
                foil_high: 1117.07,
                foil_market: 43.9,
                normal_low: -65.85,
                normal_mid: 21.95,
                normal_high: 809.76,
                normal_market: -2.44,
              },
              date_purchased: '2019-12-31',
              quantity: 5,
              single_cost: '0.41',
              price: '0.25',
              total_cash: '2.03',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'MMX Gaming',
              card: 1679,
            },
            {
              id: 4226,
              price_percentages: {
                foil_low: -30.95,
                foil_mid: 138.1,
                foil_high: 1088.1,
                foil_market: 40.48,
                normal_low: -66.67,
                normal_mid: 19.05,
                normal_high: 788.1,
                normal_market: -4.76,
              },
              date_purchased: '2019-12-31',
              quantity: 6,
              single_cost: '0.42',
              price: '0.25',
              total_cash: '2.49',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Game Heroes',
              card: 1679,
            },
          ],
        },
        '1680': {
          id: 1680,
          card_name: 'Syr Konrad, the Grim',
          set_name: 'Throne of Eldraine',
          language: '',
          foil: 1,
          tcg_productId: 198407,
          tcg_imageUrl:
            'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/198407_200w.jpg',
          tcg_groupId: 2494,
          tcg_url:
            'https://store.tcgplayer.com/magic/throne-of-eldraine/syr-konrad-the-grim',
          tcg_price: {
            id: 5407,
            date: '2020-08-04',
            product_id: 198407,
            low_price: '2.42',
            mid_price: '3.83',
            high_price: '5.88',
            market_price: '3.03',
            direct_low_price: '2.42',
            sub_type_name: 'Foil',
            card: 1680,
          },
          spec_prices: [
            {
              id: 4247,
              price_percentages: {
                foil_low: 28.04,
                foil_mid: 102.65,
                foil_high: 211.11,
                foil_market: 60.32,
                normal_low: -92.59,
                normal_mid: -77.25,
                normal_high: 59.26,
                normal_market: -82.54,
              },
              date_purchased: '2020-01-07',
              quantity: 2,
              single_cost: '1.89',
              price: '1.50',
              total_cash: '3.78',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Motor City MTG',
              card: 1680,
            },
            {
              id: 4242,
              price_percentages: {
                foil_low: 22.22,
                foil_mid: 93.43,
                foil_high: 196.97,
                foil_market: 53.03,
                normal_low: -92.93,
                normal_mid: -78.28,
                normal_high: 52.02,
                normal_market: -83.33,
              },
              date_purchased: '2020-01-07',
              quantity: 1,
              single_cost: '1.98',
              price: '1.20',
              total_cash: '1.98',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Monte Cristo Cards',
              card: 1680,
            },
            {
              id: 4243,
              price_percentages: {
                foil_low: 22.22,
                foil_mid: 93.43,
                foil_high: 196.97,
                foil_market: 53.03,
                normal_low: -92.93,
                normal_mid: -78.28,
                normal_high: 52.02,
                normal_market: -83.33,
              },
              date_purchased: '2020-01-07',
              quantity: 1,
              single_cost: '1.98',
              price: '1.20',
              total_cash: '1.98',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Gamers Only',
              card: 1680,
            },
            {
              id: 4241,
              price_percentages: {
                foil_low: 22.22,
                foil_mid: 93.43,
                foil_high: 196.97,
                foil_market: 53.03,
                normal_low: -92.93,
                normal_mid: -78.28,
                normal_high: 52.02,
                normal_market: -83.33,
              },
              date_purchased: '2020-01-07',
              quantity: 1,
              single_cost: '1.98',
              price: '1.20',
              total_cash: '1.98',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Snap Sell',
              card: 1680,
            },
            {
              id: 4244,
              price_percentages: {
                foil_low: 21.61,
                foil_mid: 92.46,
                foil_high: 195.48,
                foil_market: 52.26,
                normal_low: -92.96,
                normal_mid: -78.39,
                normal_high: 51.26,
                normal_market: -83.42,
              },
              date_purchased: '2020-01-07',
              quantity: 4,
              single_cost: '1.99',
              price: '1.99',
              total_cash: '7.96',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'MTG Card World',
              card: 1680,
            },
            {
              id: 4246,
              price_percentages: {
                foil_low: 20.4,
                foil_mid: 90.55,
                foil_high: 192.54,
                foil_market: 50.75,
                normal_low: -93.03,
                normal_mid: -78.61,
                normal_high: 49.75,
                normal_market: -83.58,
              },
              date_purchased: '2020-01-07',
              quantity: 8,
              single_cost: '2.01',
              price: '1.89',
              total_cash: '16.11',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'mtgmintcard',
              card: 1680,
            },
            {
              id: 4245,
              price_percentages: {
                foil_low: 11.01,
                foil_mid: 75.69,
                foil_high: 169.72,
                foil_market: 38.99,
                normal_low: -93.58,
                normal_mid: -80.28,
                normal_high: 38.07,
                normal_market: -84.86,
              },
              date_purchased: '2020-01-07',
              quantity: 1,
              single_cost: '2.18',
              price: '1.40',
              total_cash: '2.18',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'The Magic Corner',
              card: 1680,
            },
            {
              id: 4248,
              price_percentages: {
                foil_low: -3.59,
                foil_mid: 52.59,
                foil_high: 134.26,
                foil_market: 20.72,
                normal_low: -94.42,
                normal_mid: -82.87,
                normal_high: 19.92,
                normal_market: -86.85,
              },
              date_purchased: '2020-01-07',
              quantity: 1,
              single_cost: '2.51',
              price: '1.73',
              total_cash: '2.51',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Card-Collecting - Only sent one',
              card: 1680,
            },
          ],
        },
        '1681': {
          id: 1681,
          card_name: 'Nylea, Keen-Eyed (Showcase)',
          set_name: 'Theros Beyond Death',
          language: '',
          foil: 0,
          tcg_productId: 206696,
          tcg_imageUrl:
            'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/206696_200w.jpg',
          tcg_groupId: 2568,
          tcg_url:
            'https://store.tcgplayer.com/magic/theros-beyond-death/nylea-keen-eyed-showcase',
          tcg_price: {
            id: 5409,
            date: '2020-08-04',
            product_id: 206696,
            low_price: '2.77',
            mid_price: '4.41',
            high_price: '10.70',
            market_price: '3.75',
            direct_low_price: '4.01',
            sub_type_name: 'Normal',
            card: 1681,
          },
          spec_prices: [
            {
              id: 4261,
              price_percentages: {
                foil_low: -54.55,
                foil_mid: -28.73,
                foil_high: 247.27,
                foil_market: -38.33,
                normal_low: -77.07,
                normal_mid: -63.49,
                normal_high: -11.42,
                normal_market: -68.96,
              },
              date_purchased: '2020-01-10',
              quantity: 3,
              single_cost: '12.08',
              price: '11.99',
              total_cash: '36.24',
              total_credit: null,
              condition: 'NM',
              vendor: 'CoolStuffInc',
              notes: '',
              card: 1681,
            },
            {
              id: 4260,
              price_percentages: {
                foil_low: -55,
                foil_mid: -29.43,
                foil_high: 243.85,
                foil_market: -38.93,
                normal_low: -77.3,
                normal_mid: -63.85,
                normal_high: -12.3,
                normal_market: -69.26,
              },
              date_purchased: '2020-01-09',
              quantity: 3,
              single_cost: '12.20',
              price: '11.99',
              total_cash: '36.60',
              total_credit: null,
              condition: 'NM',
              vendor: 'CoolStuffInc',
              notes: '',
              card: 1681,
            },
            {
              id: 4249,
              price_percentages: {
                foil_low: -56.53,
                foil_mid: -31.83,
                foil_high: 232.15,
                foil_market: -41.01,
                normal_low: -78.07,
                normal_mid: -65.08,
                normal_high: -15.28,
                normal_market: -70.31,
              },
              date_purchased: '2020-01-07',
              quantity: 6,
              single_cost: '12.63',
              price: '11.99',
              total_cash: '75.79',
              total_credit: null,
              condition: 'NM',
              vendor: 'CoolStuffInc',
              notes: '',
              card: 1681,
            },
          ],
        },
        '1682': {
          id: 1682,
          card_name: 'Aethersphere Harvester',
          set_name: 'Aether Revolt',
          language: '',
          foil: 1,
          tcg_productId: 126451,
          tcg_imageUrl:
            'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/126451_200w.jpg',
          tcg_groupId: 1857,
          tcg_url:
            'https://store.tcgplayer.com/magic/aether-revolt/aethersphere-harvester',
          tcg_price: {
            id: 5411,
            date: '2020-08-04',
            product_id: 126451,
            low_price: '0.78',
            mid_price: '2.00',
            high_price: '9.49',
            market_price: '1.67',
            direct_low_price: '2.19',
            sub_type_name: 'Foil',
            card: 1682,
          },
          spec_prices: [
            {
              id: 4250,
              price_percentages: {
                foil_low: -27.78,
                foil_mid: 85.19,
                foil_high: 778.7,
                foil_market: 54.63,
                normal_low: -90.74,
                normal_mid: -53.7,
                normal_high: 1233.33,
                normal_market: -67.59,
              },
              date_purchased: '2020-01-08',
              quantity: 23,
              single_cost: '1.08',
              price: '1.04',
              total_cash: '24.91',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'ChannelFireball',
              card: 1682,
            },
            {
              id: 4265,
              price_percentages: {
                foil_low: -30.97,
                foil_mid: 76.99,
                foil_high: 739.82,
                foil_market: 47.79,
                normal_low: -91.15,
                normal_mid: -55.75,
                normal_high: 1174.34,
                normal_market: -69.03,
              },
              date_purchased: '2020-01-10',
              quantity: 25,
              single_cost: '1.13',
              price: '1.25',
              total_cash: '21.54',
              total_credit: '6.59',
              condition: 'NM',
              vendor: 'Channelfireball',
              notes: '',
              card: 1682,
            },
          ],
        },
        '1683': {
          id: 1683,
          card_name: 'Cavalier of Dawn',
          set_name: 'Core Set 2020',
          language: '',
          foil: 0,
          tcg_productId: 192830,
          tcg_imageUrl:
            'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/192830_200w.jpg',
          tcg_groupId: 2441,
          tcg_url:
            'https://store.tcgplayer.com/magic/core-set-2020/cavalier-of-dawn',
          tcg_price: {
            id: 5414,
            date: '2020-08-04',
            product_id: 192830,
            low_price: '0.99',
            mid_price: '2.67',
            high_price: '12.01',
            market_price: '2.24',
            direct_low_price: '2.83',
            sub_type_name: 'Normal',
            card: 1683,
          },
          spec_prices: [
            {
              id: 4257,
              price_percentages: {
                foil_low: 7.55,
                foil_mid: 79.86,
                foil_high: 511.51,
                foil_market: 72.66,
                normal_low: -64.39,
                normal_mid: -3.96,
                normal_high: 332.01,
                normal_market: -19.42,
              },
              date_purchased: '2020-01-08',
              quantity: 1,
              single_cost: '2.78',
              price: '2.00',
              total_cash: '2.78',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Smokesailboatgaming',
              card: 1683,
            },
            {
              id: 4256,
              price_percentages: {
                foil_low: 0,
                foil_mid: 67.22,
                foil_high: 468.56,
                foil_market: 60.54,
                normal_low: -66.89,
                normal_mid: -10.7,
                normal_high: 301.67,
                normal_market: -25.08,
              },
              date_purchased: '2020-01-08',
              quantity: 1,
              single_cost: '2.99',
              price: '2.21',
              total_cash: '2.99',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'MTgames',
              card: 1683,
            },
            {
              id: 4259,
              price_percentages: {
                foil_low: -1.64,
                foil_mid: 64.47,
                foil_high: 459.21,
                foil_market: 57.89,
                normal_low: -67.43,
                normal_mid: -12.17,
                normal_high: 295.07,
                normal_market: -26.32,
              },
              date_purchased: '2020-01-08',
              quantity: 3,
              single_cost: '3.04',
              price: '3.04',
              total_cash: '9.12',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Card Rush',
              card: 1683,
            },
            {
              id: 4253,
              price_percentages: {
                foil_low: -5.97,
                foil_mid: 57.23,
                foil_high: 434.59,
                foil_market: 50.94,
                normal_low: -68.87,
                normal_mid: -16.04,
                normal_high: 277.67,
                normal_market: -29.56,
              },
              date_purchased: '2020-01-08',
              quantity: 1,
              single_cost: '3.18',
              price: '1.93',
              total_cash: '3.18',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Bayside Thrift',
              card: 1683,
            },
            {
              id: 4255,
              price_percentages: {
                foil_low: -7.43,
                foil_mid: 54.8,
                foil_high: 426.32,
                foil_market: 48.61,
                normal_low: -69.35,
                normal_mid: -17.34,
                normal_high: 271.83,
                normal_market: -30.65,
              },
              date_purchased: '2020-01-08',
              quantity: 1,
              single_cost: '3.23',
              price: '2.24',
              total_cash: '3.23',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Heartless Summoning',
              card: 1683,
            },
            {
              id: 4254,
              price_percentages: {
                foil_low: -8,
                foil_mid: 53.85,
                foil_high: 423.08,
                foil_market: 47.69,
                normal_low: -69.54,
                normal_mid: -17.85,
                normal_high: 269.54,
                normal_market: -31.08,
              },
              date_purchased: '2020-01-08',
              quantity: 1,
              single_cost: '3.25',
              price: '2.47',
              total_cash: '3.25',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Great Stories',
              card: 1683,
            },
            {
              id: 4252,
              price_percentages: {
                foil_low: -8.28,
                foil_mid: 53.37,
                foil_high: 421.47,
                foil_market: 47.24,
                normal_low: -69.63,
                normal_mid: -18.1,
                normal_high: 268.4,
                normal_market: -31.29,
              },
              date_purchased: '2020-01-08',
              quantity: 1,
              single_cost: '3.26',
              price: '2.27',
              total_cash: '3.26',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'MexaSushi',
              card: 1683,
            },
            {
              id: 4251,
              price_percentages: {
                foil_low: -8.84,
                foil_mid: 52.44,
                foil_high: 418.29,
                foil_market: 46.34,
                normal_low: -69.82,
                normal_mid: -18.6,
                normal_high: 266.16,
                normal_market: -31.71,
              },
              date_purchased: '2020-01-08',
              quantity: 1,
              single_cost: '3.28',
              price: '2.50',
              total_cash: '3.28',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'JDM Games',
              card: 1683,
            },
            {
              id: 4258,
              price_percentages: {
                foil_low: -11.01,
                foil_mid: 48.81,
                foil_high: 405.95,
                foil_market: 42.86,
                normal_low: -70.54,
                normal_mid: -20.54,
                normal_high: 257.44,
                normal_market: -33.33,
              },
              date_purchased: '2020-01-08',
              quantity: 1,
              single_cost: '3.36',
              price: '2.37',
              total_cash: '3.36',
              total_credit: null,
              condition: 'NM',
              vendor: 'TCG Player',
              notes: 'Game Haven St George',
              card: 1683,
            },
          ],
        },
        '1912': {
          id: 1912,
          card_name: 'Obosh, the Preypiercer (Extended Art)',
          set_name: 'Ikoria: Lair of Behemoths',
          language: '',
          foil: 1,
          tcg_productId: 212638,
          tcg_imageUrl:
            'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/212638_200w.jpg',
          tcg_groupId: 2603,
          tcg_url:
            'https://store.tcgplayer.com/magic/ikoria-lair-of-behemoths/obosh-the-preypiercer-extended-art',
          tcg_price: {
            id: 5867,
            date: '2020-08-04',
            product_id: 212638,
            low_price: '6.51',
            mid_price: '10.31',
            high_price: '45.00',
            market_price: '7.49',
            direct_low_price: '7.12',
            sub_type_name: 'Foil',
            card: 1912,
          },
          spec_prices: [
            {
              id: 4732,
              price_percentages: {
                foil_low: 59.95,
                foil_mid: 153.32,
                foil_high: 1005.65,
                foil_market: 84.03,
                normal_low: -69.29,
                normal_mid: -43.98,
                normal_high: 262.41,
                normal_market: -57.99,
              },
              date_purchased: '2020-08-04',
              quantity: 1,
              single_cost: '4.07',
              price: '4.07',
              total_cash: '4.07',
              total_credit: null,
              condition: 'NM',
              vendor: 'Opened Box',
              notes: '24 Pack IKO CB',
              card: 1912,
            },
          ],
        },
        '1913': {
          id: 1913,
          card_name: "Offspring's Revenge (Extended Art)",
          set_name: 'Ikoria: Lair of Behemoths',
          language: '',
          foil: 1,
          tcg_productId: 212634,
          tcg_imageUrl:
            'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/212634_200w.jpg',
          tcg_groupId: 2603,
          tcg_url:
            'https://store.tcgplayer.com/magic/ikoria-lair-of-behemoths/offsprings-revenge-extended-art',
          tcg_price: {
            id: 5869,
            date: '2020-08-04',
            product_id: 212634,
            low_price: '0.74',
            mid_price: '1.50',
            high_price: '15.99',
            market_price: '1.14',
            direct_low_price: null,
            sub_type_name: 'Foil',
            card: 1913,
          },
          spec_prices: [
            {
              id: 4733,
              price_percentages: {
                foil_low: -25.25,
                foil_mid: 51.52,
                foil_high: 1515.15,
                foil_market: 15.15,
                normal_low: -89.9,
                normal_mid: -29.29,
                normal_high: 656.57,
                normal_market: -54.55,
              },
              date_purchased: '2020-08-04',
              quantity: 1,
              single_cost: '0.99',
              price: '0.99',
              total_cash: '0.99',
              total_credit: null,
              condition: 'NM',
              vendor: 'Opened Box',
              notes: '24 Pack IKO CB',
              card: 1913,
            },
          ],
        },
        '1914': {
          id: 1914,
          card_name: 'Kogla, the Titan Ape (Extended Art)',
          set_name: 'Ikoria: Lair of Behemoths',
          language: '',
          foil: 1,
          tcg_productId: 212083,
          tcg_imageUrl:
            'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/212083_200w.jpg',
          tcg_groupId: 2603,
          tcg_url:
            'https://store.tcgplayer.com/magic/ikoria-lair-of-behemoths/kogla-the-titan-ape-extended-art',
          tcg_price: {
            id: 5871,
            date: '2020-08-04',
            product_id: 212083,
            low_price: '6.90',
            mid_price: '9.80',
            high_price: '20.00',
            market_price: '7.97',
            direct_low_price: null,
            sub_type_name: 'Foil',
            card: 1914,
          },
          spec_prices: [
            {
              id: 4735,
              price_percentages: {
                foil_low: 50.33,
                foil_mid: 113.51,
                foil_high: 335.73,
                foil_market: 73.64,
                normal_low: -65.36,
                normal_mid: -44.88,
                normal_high: 444.66,
                normal_market: -52.94,
              },
              date_purchased: '2020-08-04',
              quantity: 1,
              single_cost: '4.59',
              price: '4.59',
              total_cash: '4.59',
              total_credit: null,
              condition: 'NM',
              vendor: 'Opened Box',
              notes: '24 Pack IKO CB',
              card: 1914,
            },
          ],
        },
        '1915': {
          id: 1915,
          card_name: 'Whirlwind of Thought (Extended Art)',
          set_name: 'Ikoria: Lair of Behemoths',
          language: '',
          foil: 1,
          tcg_productId: 212793,
          tcg_imageUrl:
            'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/212793_200w.jpg',
          tcg_groupId: 2603,
          tcg_url:
            'https://store.tcgplayer.com/magic/ikoria-lair-of-behemoths/whirlwind-of-thought-extended-art',
          tcg_price: {
            id: 5874,
            date: '2020-08-04',
            product_id: 212793,
            low_price: '5.10',
            mid_price: '6.54',
            high_price: '29.99',
            market_price: '6.23',
            direct_low_price: '6.44',
            sub_type_name: 'Foil',
            card: 1915,
          },
          spec_prices: [
            {
              id: 4736,
              price_percentages: {
                foil_low: 46.13,
                foil_mid: 87.39,
                foil_high: 759.31,
                foil_market: 78.51,
                normal_low: -70.49,
                normal_mid: -35.24,
                normal_high: 358.17,
                normal_market: -51,
              },
              date_purchased: '2020-08-04',
              quantity: 1,
              single_cost: '3.49',
              price: '3.49',
              total_cash: '3.49',
              total_credit: null,
              condition: 'NM',
              vendor: 'Opened Box',
              notes: '24 Pack IKO CB',
              card: 1915,
            },
          ],
        },
        '1916': {
          id: 1916,
          card_name: 'Gyruda, Doom of Depths (Extended Art)',
          set_name: 'Ikoria: Lair of Behemoths',
          language: '',
          foil: 1,
          tcg_productId: 212018,
          tcg_imageUrl:
            'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/212018_200w.jpg',
          tcg_groupId: 2603,
          tcg_url:
            'https://store.tcgplayer.com/magic/ikoria-lair-of-behemoths/gyruda-doom-of-depths-extended-art',
          tcg_price: {
            id: 5876,
            date: '2020-08-04',
            product_id: 212018,
            low_price: '3.25',
            mid_price: '6.53',
            high_price: '60.00',
            market_price: '4.15',
            direct_low_price: null,
            sub_type_name: 'Foil',
            card: 1916,
          },
          spec_prices: [
            {
              id: 4737,
              price_percentages: {
                foil_low: 33.2,
                foil_mid: 167.62,
                foil_high: 2359.02,
                foil_market: 70.08,
                normal_low: -62.7,
                normal_mid: -4.92,
                normal_high: 2768.44,
                normal_market: -53.69,
              },
              date_purchased: '2020-08-04',
              quantity: 1,
              single_cost: '2.44',
              price: '2.44',
              total_cash: '2.44',
              total_credit: null,
              condition: 'NM',
              vendor: 'Opened Box',
              notes: '24 Pack IKO CB',
              card: 1916,
            },
          ],
        },
      },
    },
    result: [1679, 1680, 1681, 1682, 1683, 1912, 1913, 1914, 1915, 1916],
  },
  cardReducer: {
    id: 1679,
    card_name: 'Linden, the Steadfast Queen',
    set_name: 'Throne of Eldraine',
    language: '',
    foil: 0,
    tcg_productId: 199209,
    tcg_imageUrl:
      'https://6d4be195623157e28848-7697ece4918e0a73861de0eb37d08968.ssl.cf1.rackcdn.com/199209_200w.jpg',
    tcg_groupId: 2494,
    tcg_url:
      'https://store.tcgplayer.com/magic/throne-of-eldraine/linden-the-steadfast-queen',
    tcg_price: 5406,
    spec_prices: [4231, 4229, 4230, 4228, 4227, 4226],
  },
  isLoadingReducer: {
    cards: false,
    card: false,
  },
  specPricesReducer: {
    '4226': {
      id: 4226,
      price_percentages: {
        foil_low: -30.95,
        foil_mid: 138.1,
        foil_high: 1088.1,
        foil_market: 40.48,
        normal_low: -66.67,
        normal_mid: 19.05,
        normal_high: 788.1,
        normal_market: -4.76,
      },
      date_purchased: '2019-12-31',
      quantity: 6,
      single_cost: '0.42',
      price: '0.25',
      total_cash: '2.49',
      total_credit: null,
      condition: 'NM',
      vendor: 'TCG Player',
      notes: 'Game Heroes',
      card: 1679,
    },
    '4227': {
      id: 4227,
      price_percentages: {
        foil_low: -29.27,
        foil_mid: 143.9,
        foil_high: 1117.07,
        foil_market: 43.9,
        normal_low: -65.85,
        normal_mid: 21.95,
        normal_high: 809.76,
        normal_market: -2.44,
      },
      date_purchased: '2019-12-31',
      quantity: 5,
      single_cost: '0.41',
      price: '0.25',
      total_cash: '2.03',
      total_credit: null,
      condition: 'NM',
      vendor: 'TCG Player',
      notes: 'MMX Gaming',
      card: 1679,
    },
    '4228': {
      id: 4228,
      price_percentages: {
        foil_low: -23.68,
        foil_mid: 163.16,
        foil_high: 1213.16,
        foil_market: 55.26,
        normal_low: -63.16,
        normal_mid: 31.58,
        normal_high: 881.58,
        normal_market: 5.26,
      },
      date_purchased: '2019-12-31',
      quantity: 6,
      single_cost: '0.38',
      price: '0.25',
      total_cash: '2.28',
      total_credit: null,
      condition: 'NM',
      vendor: 'TCG Player',
      notes: 'Slick Deals',
      card: 1679,
    },
    '4229': {
      id: 4229,
      price_percentages: {
        foil_low: -12.12,
        foil_mid: 203.03,
        foil_high: 1412.12,
        foil_market: 78.79,
        normal_low: -57.58,
        normal_mid: 51.52,
        normal_high: 1030.3,
        normal_market: 21.21,
      },
      date_purchased: '2019-12-31',
      quantity: 6,
      single_cost: '0.33',
      price: '0.20',
      total_cash: '1.98',
      total_credit: null,
      condition: 'NM',
      vendor: 'TCG Player',
      notes: 'gacollectables',
      card: 1679,
    },
    '4230': {
      id: 4230,
      price_percentages: {
        foil_low: -12.12,
        foil_mid: 203.03,
        foil_high: 1412.12,
        foil_market: 78.79,
        normal_low: -57.58,
        normal_mid: 51.52,
        normal_high: 1030.3,
        normal_market: 21.21,
      },
      date_purchased: '2019-12-31',
      quantity: 6,
      single_cost: '0.33',
      price: '0.20',
      total_cash: '1.98',
      total_credit: null,
      condition: 'NM',
      vendor: 'TCG Player',
      notes: 'jtsquared',
      card: 1679,
    },
    '4231': {
      id: 4231,
      price_percentages: {
        foil_low: -3.33,
        foil_mid: 233.33,
        foil_high: 1563.33,
        foil_market: 96.67,
        normal_low: -53.33,
        normal_mid: 66.67,
        normal_high: 1143.33,
        normal_market: 33.33,
      },
      date_purchased: '2019-12-31',
      quantity: 7,
      single_cost: '0.30',
      price: '0.19',
      total_cash: '2.11',
      total_credit: null,
      condition: 'NM',
      vendor: 'TCG Player',
      notes: "Dolly's Toys & Games",
      card: 1679,
    },
  },
  tcgPricesReducer: {
    '5406': {
      id: 5406,
      date: '2020-08-04',
      product_id: 199209,
      low_price: '0.14',
      mid_price: '0.50',
      high_price: '3.73',
      market_price: '0.40',
      direct_low_price: '0.37',
      sub_type_name: 'Normal',
      card: 1679,
    },
  },
};
